<?xml version="1.0"?>
<package format="3">
  <name>rangefinder_px4_bridge</name>
  <version>0.0.1</version>
  <description>Bridge a simulated downward LaserScan into PX4 DistanceSensor.</description>
  <maintainer email="petayyyy@gmail.com">sverk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
