<?xml version="1.0"?>
<package format="3">
  <name>graffiti_servo_sim</name>
  <version>0.0.1</version>
  <description>ROS 2 simulator node for the graffiti spray servo kinematics.</description>
  <maintainer email="petayyyy@gmail.com">sverk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
