<?xml version="1.0"?>
<package format="3">
  <name>mtf01_px4_bridge</name>
  <version>0.1.0</version>
  <description>Estimate MTF-01 optical flow from Gazebo images and publish PX4 SensorOpticalFlow.</description>
  <maintainer email="petayyyy@gmail.com">sverk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>cv_bridge</depend>
  <depend>px4_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <build_depend>libopencv-dev</build_depend>
  <exec_depend>libopencv-dev</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
